name: Python-Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 원격 저장소에 있는 소스코드 옮겨짐
      - name: Checkout code
        uses: actions/checkout@v4

      # 실행할 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify your desired Python version here

      - name: Run unit tests
        run: |
          python -m unittest discover -s . -p "test_*.py"
